import requests
import sys
import os
from dotenv import load_dotenv
from tqdm import tqdm

load_dotenv()

FHIR_SERVER_URL = os.getenv("SERVER_URL")

medical_resources = {
    "Observation": 669898,
    "Claim": 353347,
    "MedicationRequest": 209401,
    "DiagnosticReport": 201152,
    "DocumentReference": 143946,
    "Encounter": 143946,
    "ExplanationOfBenefit": 143946,
    "Procedure": 56092,
    "Condition": 15956,
    "Immunization": 11900,
    "CarePlan": 6135,
    "CareTeam": 6135,
    "ImagingStudy": 3752,
    "Medication": 1350,
    "MedicationAdministration": 1350,
    "Patient": 1278,
    "Provenance": 1278,
    "Media": 1072,
    "Location": 1067,
    "Organization": 1067,
    "Practitioner": 1041,
    "PractitionerRole": 1041,
    "Device": 416,
    "AllergyIntolerance": 106
}

"""
Function that download the passed medical types and return a set of all unique resource types
"""
def get_unique_types(base_url, type, total_count):
    
    query_url = f"{base_url}/{i}?_count=500"
    
    unique_types = set()
    
    print(f"Connecting to: {base_url}")
    print(f"Scanning of {total_count} {type}s...")

    with tqdm(total=total_count, unit=" resource", desc="Loading") as pbar:
        while query_url:
            try:
                response = requests.get(query_url)
                response.raise_for_status()
                bundle = response.json()
            except requests.exceptions.ConnectionError:
                print(f"\nERROR: Impossibile connettersi a {base_url}.")
                sys.exit(1)
            except Exception as e:
                print(f"\nGeneric error: {e}")
                sys.exit(1)

            # Controllo se ci sono entry nel bundle
            entries = bundle.get('entry', [])
            num_entries = len(entries)

            if num_entries > 0:
                for entry in entries:
                    resource = entry.get('resource', {})
                    
                    try:
                        code_payload = resource.get('code', {})
                        
                        if 'coding' in code_payload and len(code_payload['coding']) > 0:
                            coding = code_payload['coding'][0]
                            display_name = coding.get('display', 'Name not available')
                            code_value = coding.get('code', 'NO CODE')
                            obs_type = f"{display_name} (Codice: {code_value})"
                            unique_types.add(obs_type)
                        elif 'text' in code_payload:
                            unique_types.add(f"{code_payload['text']} (Testo libero)")
                            
                    except Exception:
                        continue
                
                # Updating loading bar with all unique resources found
                pbar.update(num_entries)
                
                # Showing which resources types was found up to now
                pbar.set_postfix(Unique_types=len(unique_types))

            # Gestione PAGINAZIONE
            query_url = None
            for link in bundle.get('link', []):
                if link['relation'] == 'next':
                    query_url = link['url']
                    break

    return unique_types

if __name__ == "__main__":
    try:
        for i in medical_resources:
            types_found = get_unique_types(FHIR_SERVER_URL, i, medical_resources[i])
            
            print("\n\n" + "="*50)
            print("RESULTS")
            print("="*50)
            
            if not types_found:
                print(f"No {i} found")
            else:
                print(f"Found {len(types_found)} unique resources:\n")
                
                # Ordiniamo e stampiamo
                sorted_types = sorted(types_found)
                for t in sorted_types:
                    print(f"- {t}")
                
                # Specify the directory name
                directory_name = "info_unique_resources"

                # Create the directory
                try:
                    os.mkdir(directory_name)
                    print(f"Directory '{directory_name}' created successfully.")
                except FileExistsError:
                    print(f"Directory '{directory_name}' already exists")
                except PermissionError:
                    print(f"Permission denied: Unable to create '{directory_name}'")
                except Exception as e:
                    print(f"An error occurred: {e}")

                # File saving
                filename = f"{directory_name}/risultati_{i}.txt"
                with open(filename, "w", encoding="utf-8") as f:
                    f.write(f"Report generated by server: {FHIR_SERVER_URL}\n")
                    f.write(f"Total {i}: {medical_resources[i]}\n")
                    f.write(f"Unique types found: {len(types_found)}\n")
                    f.write("="*50 + "\n")
                    for t in sorted_types:
                        f.write(f"{t}\n")
                print("\n" + "="*50)
                print(f"Output saved in: {filename}")

    except KeyboardInterrupt:
        print("\nDeep search interrupted")